name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# Config Launcher Icons ditaruh sejajar dengan dev_dependencies
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0F2027" # Ganti dengan kode warna hex valid
    theme_color: "#203A43"      # Ganti dengan kode warna hex valid

flutter:
  uses-material-design: true

  # Pendaftaran folder/file assets
  assets:
    - assets/images/logo.png